### PR TITLE
SSDT Method: softPowerPlayTable in SSDT file

### PR DESCRIPTION
**Pull request by klich3**
Added description with tool description to convert PowerTable to hex format for insertion into SSDT

### CODE REVIEW

**Comment by perez987** [comment]
@klich3 
Thanks! Not at home, I’ll review later to merge.

**Comment by perez987** [comment]
@klich3 
Good night. I have a few comments. Tell me what do you think.
________________________________
**README.md**

You say:

> SSDT Method:
> 
> You can read [heare](./SSDT/README.md) the extraction of power play table from rom, and generated from DSDT - SSDT APCI Table.

I like something like this:

> SSDT Method:
> 
> You can read [here](./SSDT/README.md) how to extract PowerPlayTable directly from the ROM file and convert it to hexadecimal data that can be used within an SSDT file instead of writing it to the DeviceProperties key of config.plist.
________________________________
You say:

> Copy all the content into the ssdt-gfx-ppt.dsl file where the marks are indicated.

But the dsl file is named `Sample.dsl` and I don't see any marks, maybe it can be:

> Copy all the content into the `Sample.dsl` file replacing its current PP_PhmSoftWTTable value with yours. `Sample.dsl` can be renamed to something more specific such as `SSDT-GFX-PPT.dsl`. Remember not to use the DSL code file but the compiled AML file.
________________________________
**./SSDT/README.md**

You say:

> (Note: Remember to delete last comma after "0x00 , 0x76 , 0x00 , 0x00 , 0x00 , 0x00 , 0x00 , // <------")

Do you mean removing the last comma from the hexadecimal string, as I think it should be? Because the hexadecimal numbers may not match other users. If it is as I think, it would be better to write
`(Note: Remember to delete last comma of the hex string)`
without specifying numbers.
Or do you mean delete the last comma from a different row?
This information is not entirely clear in the text.
________________________________
If the table converted with `to-hex.sh` starts with PP_PhmSoftWTTable instead of PP_PhmSoftPowerPlayTable (as happens to me), should it be passed to the SSDT under "PP_PhmSoftWTTable" or should the property be renamed to "PhmSoftPowerPlayTable"?
________________________________
**./SSDT/Sample.dsl**

The first block is confusing, `_SB_.PCI0.GFX0` creates doubts with `_SB_.PCI0.PEG0`, maybe it is better to write only a classical scope like this

```
External (_SB_.PCI0, DeviceObj)
External (_SB_.PCI0.PEG0, DeviceObj)
External (_SB_.PCI0.PEG0.PEGP, DeviceObj)
```
     
reminding the user to check if their IOReg path is different.
________________________________
I think that this code is not necessary, it can be commented or removed.

 ```
// Write the preferred GPU index here (1-4)
"AAPL,slot-name",
Buffer()
{
 	"Slot-1"
},

// Write the main monitor index (currently 0) here, the value does not matter
"@0,AAPL,boot-display",
Buffer(Zero){}
```
 ________________________________
The example code for IGPU injection `Device (IMEI) / Scope (GFX0) / Device (IGPU)` is under the comment
`// Below goes an example for IGPU injection useful for enabling hardware video decoding and other stuff`.
Since this code is not intended for regular use and most of us do not use it, I think it would be better if the entire code block were commented, so that it is not compiled by default but only when the user wants to do so.
________________________________

Waiting for your comments but I tell you that the PR seems very interesting to me since writing the sPPT string to an SSDT instead of to config.plist is a rarely discussed topic and even I myself have failed to do it when I wanted to do it.
So I am very interested in improving my repo with this contribution.

**Comment by klich3** [comment]
Question: If the table converted with to-hex.sh starts with PP_PhmSoftWTTable instead of PP_PhmSoftPowerPlayTable (as happens to me), should it be passed to the SSDT under "PP_PhmSoftWTTable" or should the property be renamed to "PhmSoftPowerPlayTable"?
Answer: I have found the two options, both are equally useful, although the most known is `PP_PhmSoftPowerPlayTable` so I have modified the code so that it is like this and there are no problems.
________________________________
Question: The first block is confusing, _SB_.PCI0.GFX0 creates doubts with _SB_.PCI0.PEG0, maybe it is better to write only a classical scope like this
Answer: When saving as AML the final result is formatted correctly.
________________________________
For the rest the file is an original iMacPro1,1 dump, of course each user has to modify it according to his hardware. It may be that it detects everything correctly and we just want to add the PPT to the system. In this case we delete everything unnecessary.

Thank you for your comments, according to which I have extended and modified the texts to make them more understandable.

**Comment by perez987** [comment]
@klich3 

- Minor formatting and text changes.
- Added note to get `to-hex.sh` output as text file.
- Removed the alternative option PP_PhmSoftWTTable since now the script writes PP_PhmSoftPowerPlayTable as default property.
- `Buffer(<value>)` is the hexadecimal count of hexadecimal numbers + 1?
Or the count of hexadecimal numbers without adding 1?
Because I open the text in BBEdit and the words count is 2470 decimal = 0x9A6 hexadecimal, without the need of adding 1.
- Added note about compiler filling in the buffer value in a automatic mode if in DSL code it has no value, so no need to convert from decimal to hex.

Regards, Emilio.

**Comment by perez987** [comment]
@klich3 
There are 2 more things I'm thinking about.

**1. sPPT changed / unchanged**
My repo shows how to bring into OpenCore's config.plist an sPPT string that has been modified in Windows to disable the Zero RPM option and get the AMD card to run on macOS at a lower temperature.
Your PR shows how to bring the sPPT string to an SSDT, but the string is extracted directly from the dGPU so it is unmodified, as it comes from factory, with Zero RPM enabled.
The option to port the string to an SSDT is very interesting, this is something that some users, including myself, will appreciate.
But what others are looking for is to have the sPPT string in macOS modified so that graphics fans spin longer and card temperature is lower.
They are 2 different topics.

Your PR can hold the instructions for extracting the ROM and convert it to a string capable of being written to an SSDT file.
I might later edit the text to have 2 options in SSDT mode:

- sPPT extracted from unmodified ROM (your PR)
- sPPT extracted from Windows registry after disabling Zero RPM with More Power Tool.

Both options end up integrating the sPPT string into the SSDT file.

**2. SSDT too complex** (imo)
Your sample SSDT is excessively complex, most users do not know or use many of the properties it contains. I believe that a much simpler SSDT should be offered, imitating those that already exist to adjust AMD cards in macOS, e.g. SSDT-BRG0, SSDT-NAVI, etc.
These SSDTs allow you to add the sPPT string in hexadecimal mode but their content is much simpler, just enough to show the user how to do the task but without complicating it with unnecessary properties.
Something like this:
```c++
DefinitionBlock ("", "SSDT", 2, "DRTNIA", "AMDGPU", 0x00001000)
{	
    External (_SB_.PCI0, DeviceObj)
    External (_SB_.PCI0.PEG0.PEGP, DeviceObj)

    Scope (\_SB.PCI0.PEG0.PEGP)
    {
        If (_OSI ("Darwin"))
        {
            Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
            {
                Local0 = Package (0x02)
                {
					
				// Insert here your code

				// End mark

				}
                DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
                Return (Local0)
            }
        }
    }

    Scope (\_SB.PCI0)
    {
        Method (DTGP, 5, NotSerialized)
        {
            If ((Arg0 == ToUUID ("a0b5b7c6-1318-441c-b0c9-fe695eaf949b") /* Unknown UUID */))
            {
                If ((Arg1 == One))
                {
                    If ((Arg2 == Zero))
                    {
                        Arg4 = Buffer (One)
                            {
                                 0x03                                             // .
                            }
                        Return (One)
                    }

                    If ((Arg2 == One))
                    {
                        Return (One)
                    }
                }
            }

            Arg4 = Buffer (One)
                {
                     0x00                                             // .
                }
            Return (Zero)
        }
    }
}
```
I have tried your SSDT sample and also this simpler one based on SSDT-BRG0.
Yours requires me to slightly modify the paths to the device and SSDT-BRG0 works as is.
Both make `PP_PhmSoftPowerPlayTable` visible in IORegistry Explorer.
As expected, your SSDT keeps normal operation of the fans but, with SSDT-BRG0, fans spin when reaching 40º and card remains approx. 10º colder.

**Comment by klich3** [comment]
You are right, in both aspects, the main or the best would be to show the user the easiest option copy and paste. The extraction method your assumption is correct, it is PPT is OEM ie the fans are stopped. For them there is an excel and it can be modified. I will expand the Git with an explanation of how to modify the PPT so that they do not shut down.

Maybe it would be good to make a new `to-hex` type script but that generates the DSL.

**Comment by perez987** [comment]
@klich3 
Off topic: Estás en Barcelona? Yo vivo en León.

**Comment by perez987** [comment]
@klich3 
In order to adjust this PR to merge it, I am going to summarize previous comments to finish.

**upp / to-hex.sh**
The idea of extracting sPPT from the ROM with `upp` and converting it with `to-hex.sh` script is very valid and should remain in the PR. I see that part ok.

**Sample.dsl**
In agreement with my previous comment, it is too complex for the purpose we are looking for, it can confuse users. I prefer to include the SSDT code that I added above, the file can be called `SSDT-sample.dsl` or whatever you prefer.

If you agree, go ahead with it, make the necessary changes to merge the PR.
__________
Regarding a new `to-hex`, you can think about it although I do not see essential that the script also generates the DSL file since it can be downloaded from the repo and it is easy to copy and paste the string in the right place.
For my part, I have tried to imitate the `to-hex` script so that it acts on the sPPT key, saved from the Windows registry, and get the code suitable for SSDT but my knowledge of regex and sed is poor and I always have errors.
This second `to-hex` when acting on the registry file (named e.g. Windows-registry.reg or Windows-registry.txt) should perform these actions:
__________
1. Remove lines 1-3

2. Remove `"PP_PhmSoftPowerPlayTable"=hex:` before first hex number

3. Remove backslashes at the end of lines

4. Remove spaces at the beginning of the lines starting from line 2

5. Remove line breaks leaving the string on a single line to make it easier to paste it into the destination file (compiler makes changes to format the string in the right way when producing the AML file)

6. Replace commas by ` . 0x` (note space before and after the period)

7. Add `0x` at the beginning of the text, before first hex number

8. Add these 3 lines at the beginning of the text:
```
"PP_PhmSoftPowerPlayTable", 
Buffer ()
{
```
Note: compiler calculates buffer length and writes it   
9. Add this kine at the end of the text:
`}`
        
The result must be the same:

```
"PP_PhmSoftPowerPlayTable", 
Buffer ()
{
0xA6, 0x09, 0x12, 0x00, 0x02, 0x22, 0x03, 0xAE, 0x09, ... / ... (long string)
}
```
__________
These are the actions that I have tried to set in a script with regex and/or sed but I have no success so far.

Regards, Emilio.

**Comment by klich3** [comment]
@perez987 Si así es soy de Barcelona :) en breve haré los cambios que comentamos en los comments anteriores.

**Comment by perez987** [comment]
@klich3 
Only as info, for a hypothetic future work, these are the Windows registry files.

- [1SoftPowerPlayTable-key.txt](https://github.com/perez987/6600XT-on-macOS-with-PowerPlayTable/files/13418197/1SoftPowerPlayTable-key.txt) -> registry key exported on Windows
- [2SoftPowerPlayTable-key.txt](https://github.com/perez987/6600XT-on-macOS-with-PowerPlayTable/files/13418198/2SoftPowerPlayTable-key.txt) -> modified by actions listed above.

**Comment by perez987** [comment]
> @perez987 Si así es soy de Barcelona :) en breve haré los cambios que comentamos en los comments anteriores.

Encantado, hasta hoy no me he fijado en que pone Barcelona en tu perfil de GitHub.
Yo llevo muchos años en León pero soy madrileño, nacido y criado en Chamberí así que teóricamente castizo pero para vivir no me gustaba.
Gracias por la aportación, yo me he dado cuenta al leerte que tengo que aprender sed y expresiones regulares.
Un saludo.

**Comment by klich3** [comment]
> > @perez987 Si así es soy de Barcelona :) en breve haré los cambios que comentamos en los comments anteriores.
> 
> Encantado, hasta hoy no me he fijado en que pone Barcelona en tu perfil de GitHub. Yo llevo muchos años en León pero soy madrileño, nacido y criado en Chamberí así que teóricamente castizo pero para vivir no me gustaba. Gracias por la aportación, yo me he dado cuenta al leerte que tengo que aprender sed y expresiones regulares. Un saludo.

Si siempre se aprende algo nuevo :).
El script de `to-hex` lo he ampliado para que sea mas fácil. Añadiré un ejemplo de ROM exports de Windows y Los del otro script. El Readme de la descripción tambien lo estoy reestructurando para que se entienda bien. Aun que el tema de ACPI es bastante extenso.

**Comment by perez987** [comment]
@klich3 
Thank you! I’ll review it later.

**Comment by klich3** [comment]
Great, now I have added two tools to be able to pull PPTs from different Windows Reg exports. Editor just to copy and paste into the final DSL.

After that if all stuff is correct merge it.
Regards

**Comment by perez987** [comment]
Good night. Yes, I see now the improvements made. Excellent idea the script to convert directly from REG file to HEX code so one can change the ROM in Windows with MorePower Tools and write the obtained sPPT into an SSDT.

**1.**
`pp_table-to-hex-dsl.sh`
I get an error, this is the output:
```
/Users/yo/Desktop > sh ./pp_table-to-hex-dsl.sh
		"PP_PhmSoftPowerPlayTable",
		Buffer ()
		{
./pp_table-to-hex-dsl.sh: line 40: syntax error near unexpected token `<'
./pp_table-to-hex-dsl.sh: line 40: `done < <(xxd -u -g 1 < "$thefile")'
```

**2.**
`win-reg-to-hex-dsl.sh`

The string is well build but I get `-e` at the beginning of the lines:

```
/Users/yo/Desktop > sh ./win-reg-to-hex-dsl.sh 1SoftPowerPlayTable.reg 
"PP_PhmSoftPowerPlayTable",
-e 	Buffer ()
-e 	{
-e 0xA6,0x09,0x12,0x00,0x02,0x22,0x03,0xAE,0x09,0x00,0x00,0x22,0x43,0x00,0x00,0x83,
... / ...
0x00,0x00,0x00,0x00,0x1E,0x06
-e 	}
```

Removing -e from last 4 lines of the script fixes the issue (HEX string now looks right).

```
#echo -e "\tBuffer ()"
#echo -e "\t{"
#echo -e "$formatted_content"
#echo -e "\t}\n"

echo "\tBuffer ()"
echo "\t{"
echo "$formatted_content"
echo "\t}\n"
```

**3.**
`win-reg-dump-TXT-to-hex-dsl.sh`

There is a blank line between hex string and last brace:

```
0x00,  0x00,  0x00,  0x00,  0x1e,  0x06 //......


	}
```

Do you think that first errors is on my side? The script work fine for you?

**Comment by perez987** [comment]
@klich3 
How do you get the REG dump? Named 000bus3-1.txt in your PR.

**Comment by klich3** [comment]
Primero hay que dar permiso para que sea ejecutable `chmod +x script.sh` y posteriormente `./script.sh <archivo>.txt` o `.reg` sin `sh` delante.

**Comment by klich3** [comment]
> @klich3 How do you get the REG dump? Named 000bus3-1.txt in your PR.

Los dos dumps son exports del propio RegEdit en Windows.

**Comment by perez987** [comment]
@klich3 
Ok. But I still have the error already mentioned when using current `pp_table-to-hex-dsl.sh`.
Old `to-hex.sh` instead produces the string ok.

```
/Users/yo/Desktop > ./pp_table-to-hex-dsl.sh 
		"PP_PhmSoftPowerPlayTable",
		Buffer ()
		{
./pp_table-to-hex-dsl.sh: line 40: syntax error near unexpected token `('
./pp_table-to-hex-dsl.sh: line 40: `done < (xxd -u -g 1 < "$thefile")'
```

He escrito en inglés para quien nos lea en inglés pero, si estás de acuerdo, seguimos en castellano hasta que mezclemos el PR y lo cerremos.

**Comment by klich3** [comment]
Se copia archivo "pp_table" en la carpeta del mismo script y se lanza "./pp_table-to-hex-dsl.sh"

**Comment by perez987** [comment]
> Se copia archivo "pp_table" en la carpeta del mismo script y se lanza "./pp_table-to-hex-dsl.sh"

Pues ahora funciona bien, no sé por qué daba ese error, en fin, que va como debe ir.

Respecto a `win-reg-to-hex-dsl.sh`, te decía que aparece `-e` antes de cada línea:

```
/Users/yo/Desktop > sh ./win-reg-to-hex-dsl.sh 1SoftPowerPlayTable.reg 
"PP_PhmSoftPowerPlayTable",
-e 	Buffer ()
-e 	{
-e 0xA6,0x09,0x12,0x00,0x02,0x22,0x03,0xAE,0x09,0x00,0x00,0x22,0x43,0x00,0x00,0x83,
... / ...
0x00,0x00,0x00,0x00,0x1E,0x06
-e 	}
```

Pero quitando -e de las 4 últimas líneas parece corregirse, ¿qué opinas?

```
#echo -e "\tBuffer ()"
#echo -e "\t{"
#echo -e "$formatted_content"
#echo -e "\t}\n"

echo "\tBuffer ()"
echo "\t{"
echo "$formatted_content"
echo "\t}\n"
```

Y respecto a `win-reg-dump-TXT-to-hex-dsl.sh` hay una línea en blanco entre la última fila hexadecimal y la llave de cierre:

```
0x00,  0x00,  0x00,  0x00,  0x1e,  0x06 //......


	}
```

**Comment by klich3** [comment]
La -e de echo es justamente para que interprete \n como salto de línea \t como tabulación y etc...

Por el espacio antes del corchete no pasa nada ya que se formatea al compilar AML.

Captura de pantalla 2023-11-22 a las 23 35 52
Captura de pantalla 2023-11-22 a las 23 35 58

**Comment by perez987** [comment]
@klich3 
Vale, mañana lo repaso para completarlo. Buenas noches.

**Comment by perez987** [comment]
@klich3 

Peticiones:

- pon en mayúsculas el nombre del SSDT `SAMPLE-NAVI21.dsl`, hay una convención de hacerlo así, al menos las letras SSDT, lo siguiente a veces se ve en minúsculas.
- Cambia el nombre de `win-reg-dump-TXT-to-hex-dsl.sh` a `win-reg-txt-to-hex-dsl.sh`, queda bien diferenciado de `win-reg-to-hex-dsl.sh `y la palabra _dump_ puede despistar a algunos usuarios.
- Cambia el nombre de `000bus3-1.txt` a algo más explícito, ejemplo `ppt-reg.txt` o como tú lo veas.

Muchas gracias, no pensé que se podía automatizar tanto la conversión de la clave del registro a la cadena para OpenCore, es una gran comodidad.

Si estás de acuerdo, por mí está bien así.

**Comment by perez987** [comment]
@klich3 

Igualmente pasa con el script `win-reg-dump-TXT-to-hex-dsl.sh` que lee del archivo de registro de Windows pero en esta ocasión guardado como TXT.

La clave "PP_PhmSoftPowerPlayTable" tiene a continuación "PP_AutoOCEngineClock" como en el archivo REG, lógicamente. Se ve así:

```
...
00000990   00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ................
000009a0   00 00 00 00 1e 06                                  ......

Valor 235
  Nombre:            PP_AutoOCEngineClock
  Tipo:            REG_DWORD
  Datos:            0
```

Y al convertir a cadena hex con el script se añade un texto relativo a "PP_AutoOCEngineClock":

```
...
0x00,  0x00,  0x00,  0x00,  0x1e,  0x06 //......

Valor 0x23, 5
  Nombre:PP_AutoO0xCE, ngin0xeC, lock
  Tipo:REG_DWORD
  0xDa, tos:0

	}
```

¿Te suceden a ti también estas 2 cosas?

**Comment by klich3** [comment]
Comparte los dos archivos que usas para yo poder ver si me pasa lo mismo, con los míos todo sale perfecto. Quizás hay que prever excepciones.

**Comment by klich3** [comment]
Hola, he hecho los cambios que me pediste, y ademas he modificado un poco los scripts
* el `pp_table-to-hex-dsl.sh` funciona igual que antes buscando el pptable en la carpeta o ahora le puedes pasar el path hasta el archivo creo que sera mas comodo y unificado
* el `win-reg-to-hex-dsl.sh` y `win-reg-txt-to-hex-dsl.sh` ahora en vez de echo uso printf debería de sacar el resultado bien sin fallos
* todos los scripts ahora sacan el mismo resultado (me refiero estilo unificado, con mismas tabulaciones).

Me he dado cuenta de que al compilar el MaciASL añade todo lo que necesita. 
Saludos

**Comment by perez987** [comment]
@klich3 
Lo fusiono ahora.
Para más adelante tengo pensado cambiar el README principal para, que al llegar a los métodos, se desglose en 2 README, uno para el método SSDT y otro para el método DeviceProperties. Ambos métodos tienen la misma importancia sino más incluso el del SSDT ya que, con tus scripts, facilita mucho la tarea y me parece que desde SSDT la cadena actúa mejor que desde DeviceProperties donde en ocasiones no se consigue el efecto buscado con Zero RPM.
¡¡¡Gracias!!!

**Comment by klich3** [comment]
Genial! Ahora es más fácil. Para mi el método de SSDT es más fácil a la hora de migrar o actualizar ya que luego con PropTree son dos clicks. 
Encartado de aportar un granito de arena al asunto 😁 
Le mando un saludo.

**Comment by perez987** [comment]
Gracias. Seguimos en contacto. Saludos, Emilio.

**Comment by perez987** [comment]
@klich3 
Buenos días, Anton, ¿sabes por qué no estás todavía entre los colaboradores del repositorio? Otras veces, cuando fusiono un PR enseguida sale el autor del PR en la lista de colaboradores. ¿Hay que hacer algo más?

Colaboradores

**Comment by klich3** [comment]
Buenos días Emilio voy a ver por si es algo de mi perfil.

**Comment by perez987** [comment]
@klich3 
Ya sales, se ve que tarda en propagar este ajuste.

Colaboradores

**Comment by klich3** [comment]
En el Móvil si que aparece.

**Comment by perez987** [comment]
@klich3 
Algo extraño, tú dices que sales en tu móvil y también sales en el mío pero yo he probado en el PC, Safari en macOS y Chrome y Edge en Windows, no te veo en la página principal del repo

Contributors1

pero sí entrando en la sección Contributors

Contributors2

He leído que a veces tarda hasta 24 horas en propagar un cambio así pero lo raro es que salgas en unos y no en otros. En fin...

**Comment by klich3** [comment]
Hola Emilio, antes de nada gracias por mencionar me en Git y en la Web :)
Acabo de descubrir de porque no aparezco como contribuidor, y es porque no coincide el email de mi cuenta con la de firma del ssh al hacer push en Git. De hecho al hacer cambio de mail la gente se queja que desaparecen sus logros y mas cositas sera que lo tienen automatizado y ha de coincidir...

Por cierto en SSDT de ejemplo hay un pequeño error en 
```
 Local0 = Package (0x02)
 ```

el 0x02 lo has de quitar, porque lo rellena el assembler al compilar AML, si no da error al compilar

Un Saludo

**Comment by perez987** [comment]
@klich3 
Faltaría más, en realidad gracias a ti que has aportado cosas muy interesantes, que están fuera de mi alcance. Ahora el texto es mucho más ilustrativo ya que haces muy sencilla la tarea y funciona mejor con SSDT que en config.plist.

Ya veo, me imaginaba que lo del contribuidor era algo relacionado con el email pero no lo tenía claro. Me gustaría mucho que tú también salieses.

Como no creo que se pueda "reparar" el email en el PR que está cerrado (y si crees que abriéndolo para modificar tu email y cerrándolo de nuevo sirve, dímelo) he pensado en que hagas un PR para ese pequeño cambio en el SSDT, con el email coincidente, lo fusiono y al menos ya tengo en el grupo.

**Pull request merged**
